<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aruforgas extends \Application\Entity\Aruforgas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'aru', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'darab', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'megjegyzes', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'tipus', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'tartozas', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'parent', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'kavefajta', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'created_at');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'aru', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'darab', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'megjegyzes', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'tipus', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'tartozas', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'parent', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'kavefajta', '' . "\0" . 'Application\\Entity\\Aruforgas' . "\0" . 'created_at');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Aruforgas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAru()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAru', array());

        return parent::getAru();
    }

    /**
     * {@inheritDoc}
     */
    public function setAru(\Application\Entity\Aru $aru = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAru', array($aru));

        return parent::setAru($aru);
    }

    /**
     * {@inheritDoc}
     */
    public function setNev($nev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNev', array($nev));

        return parent::setNev($nev);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipus($tipus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipus', array($tipus));

        return parent::setTipus($tipus);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipus', array());

        return parent::getTipus();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipusString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipusString', array());

        return parent::getTipusString();
    }

    /**
     * {@inheritDoc}
     */
    public function setTartozas(\Application\Entity\Tartozas $tartozas = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTartozas', array($tartozas));

        return parent::setTartozas($tartozas);
    }

    /**
     * {@inheritDoc}
     */
    public function getTartozas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTartozas', array());

        return parent::getTartozas();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Application\Entity\Aruforgas $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setKavefajta(\Application\Entity\Kavefajta $kavefajta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKavefajta', array($kavefajta));

        return parent::setKavefajta($kavefajta);
    }

    /**
     * {@inheritDoc}
     */
    public function getKavefajta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKavefajta', array());

        return parent::getKavefajta();
    }

    /**
     * {@inheritDoc}
     */
    public function getAruNev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAruNev', array());

        return parent::getAruNev();
    }

    /**
     * {@inheritDoc}
     */
    public function getAruEladasiAr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAruEladasiAr', array());

        return parent::getAruEladasiAr();
    }

    /**
     * {@inheritDoc}
     */
    public function getAruDarab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAruDarab', array());

        return parent::getAruDarab();
    }

    /**
     * {@inheritDoc}
     */
    public function timestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'timestamp', array());

        return parent::timestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function getDarab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDarab', array());

        return parent::getDarab();
    }

    /**
     * {@inheritDoc}
     */
    public function setDarab($darab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDarab', array($darab));

        return parent::setDarab($darab);
    }

    /**
     * {@inheritDoc}
     */
    public function getMegjegyzes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMegjegyzes', array());

        return parent::getMegjegyzes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMegjegyzes($megjegyzes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMegjegyzes', array($megjegyzes));

        return parent::setMegjegyzes($megjegyzes);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($datetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($datetime));

        return parent::setCreatedAt($datetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isEditableAndDeletable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEditableAndDeletable', array());

        return parent::isEditableAndDeletable();
    }

}
