<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ceg extends \Application\Entity\Ceg implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'cegname', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'szerzodesdatum', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'automatikushosszabbitas', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'idotartam', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'fizetesihatarido', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'szazalekmunkas');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'cegname', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'szerzodesdatum', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'automatikushosszabbitas', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'idotartam', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'fizetesihatarido', '' . "\0" . 'Application\\Entity\\Ceg' . "\0" . 'szazalekmunkas');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ceg $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCegname($cegname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCegname', array($cegname));

        return parent::setCegname($cegname);
    }

    /**
     * {@inheritDoc}
     */
    public function getCegname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCegname', array());

        return parent::getCegname();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzerzodesdatum($szerzodesdatum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzerzodesdatum', array($szerzodesdatum));

        return parent::setSzerzodesdatum($szerzodesdatum);
    }

    /**
     * {@inheritDoc}
     */
    public function getSzerzodesdatum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzerzodesdatum', array());

        return parent::getSzerzodesdatum();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutomatikushosszabbitas($automatikushosszabbitas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutomatikushosszabbitas', array($automatikushosszabbitas));

        return parent::setAutomatikushosszabbitas($automatikushosszabbitas);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutomatikushosszabbitas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutomatikushosszabbitas', array());

        return parent::getAutomatikushosszabbitas();
    }

    /**
     * {@inheritDoc}
     */
    public function setSzazalekmunkas($szazalekmunkas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSzazalekmunkas', array($szazalekmunkas));

        return parent::setSzazalekmunkas($szazalekmunkas);
    }

    /**
     * {@inheritDoc}
     */
    public function getSzazalekmunkas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSzazalekmunkas', array());

        return parent::getSzazalekmunkas();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdotartam($idotartam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdotartam', array($idotartam));

        return parent::setIdotartam($idotartam);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdotartam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdotartam', array());

        return parent::getIdotartam();
    }

    /**
     * {@inheritDoc}
     */
    public function setFizetesihatarido($fizetesihatarido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFizetesihatarido', array($fizetesihatarido));

        return parent::setFizetesihatarido($fizetesihatarido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFizetesihatarido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFizetesihatarido', array());

        return parent::getFizetesihatarido();
    }

}
