<!-- Modal -->
<div class="modal fade" id="globalModal" tabindex="-1" role="dialog" aria-labelledby="globalModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate('Bezár') ?></span></button>
        <h4 class="modal-title" id="globalModal"></h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Bezár') ?></button>
        <button type="button" class="btn btn-primary"><?php echo $this->translate('Mentés') ?></button>
      </div>
    </div>
  </div>
</div>

<div class="hide" id="modal_success"><?php echo $this->translate('A művelet sikeresen végrehajtódott!'); ?></div>
<div class="hide" id="modal_nodelete"><span class="error-text"><?php echo $this->translate('Ez a tétel nem törölhető!'); ?></span></div>
