<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('nev')); ?>
    <span class="help-block" id="help_<?php echo $form->get('nev')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('alapar')); ?>
    <span class="help-block" id="help_<?php echo $form->get('alapar')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('cegesar')); ?>
    <span class="help-block" id="help_<?php echo $form->get('cegesar')->getAttribute('id') ?>"></span>
</div>

<?php echo $this->form()->closeTag($form); ?>