<h2><?php echo $this->translate('Szolgáltatások') ?></h2>
<hr />
<div class="hide" id="modal_title_new"><?php echo $this->translate('Új szolgáltatás bevezetése'); ?></div>
<div class="hide" id="torol_confirm_text"><?php echo $this->translate('Biztosan törlöd a szolgáltatást?'); ?></div>
<div class="hide" id="modal_title_edit"><?php echo $this->translate('Szolgáltatás adatainak módosítása'); ?></div>
<div class="hide" id="modal_getformurl"><?php echo $this->url('szolgaltatas', array('action' => 'getform')) ?></div>
<div class="hide" id="modal_saveformurl"><?php echo $this->url('szolgaltatas', array('action' => 'saveform')) ?></div>
<div class="hide" id="delete_url"><?php echo $this->url('szolgaltatas', array('action' => 'delete')) ?></div>
<div class="hide" id="ajax_error_message"><?php echo $this->translate('Hiba! A műveletet nem sikerült végrehajtani!'); ?></div>
<div class="hide" id="saveFormCallbackFuncName">saveSzolgaltatasCallback</div>

<input type="hidden" id="isAllowedEdit" value="<?php echo ($this->isAllowed('szolgaltatas', 'modosit') ? 1 : 0); ?>" />
<input type="hidden" id="isAllowedDelete" value="<?php echo ($this->isAllowed('szolgaltatas', 'torol') ? 1 : 0); ?>" />
       
<?php $dataTableId = 'szolgaltatasok_table' ?>

<?php
if ($this->isAllowed('szolgaltatas', 'letrehoz')) :
    ?>

    <a href="javascript:void(0)" class="create_edit" id="object_0">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Új szolgáltatás bevitele'); ?>
    </a>
    <br /><br />
    <?php
endif;
?>

<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered myDataTable" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Szolgáltatás neve'); ?></th>
            <th><?php echo $this->translate('Ekezet nelkuli nev'); ?></th>
            <th><?php echo $this->translate('Alap ár'); ?></th>
            <th><?php echo $this->translate('Céges ár'); ?></th>
            <th><?php echo $this->translate('Műveletek'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($szolgaltatasok)) :
            foreach ($szolgaltatasok as $szolgaltatas) {
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($szolgaltatas->getNev()) ?></td>
                    <td><?php echo $this->accent_trimmer($this->escapeHtml($szolgaltatas->getNev())) ?></td>
                    <td><?php echo $this->escapeHtml($szolgaltatas->getAlapar()) ?> RON</td>
                    <td><?php echo $szolgaltatas->getCegesar() ? $this->escapeHtml($szolgaltatas->getCegesar()) . ' RON' : '-' ?></td>
                    <td>
                        <?php
                        if ($this->isAllowed('szolgaltatas', 'modosit')) :
                            ?>
                            <a href="javascript:void(0)" class="create_edit" id="object_<?php echo $szolgaltatas->getId() ?>" title="<?php echo $this->translate('Módosítás'); ?>">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <?php
                        endif;

                        if ($this->isAllowed('szolgaltatas', 'torol')) :
                            ?>
                            <a href="javascript:void(0)" class="torol" id="object_torol_<?php echo $szolgaltatas->getId() ?>" title="<?php echo $this->translate('Törlés'); ?>">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                            <?php
                        endif;
                        ?>
                    </td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
</table>

<?php echo $this->partial('/application/partial_modal.phtml'); ?>

<script>
    $(document).ready(function() {
        $("#<?php echo $dataTableId ?>").dataTable({
            language: {
                url: '/js/DataTables-1.10.2/localization/Hungarian.json'
            },
        
            "columnDefs": [
                {
                    "targets": [1],
                    "visible": false,
                },
                
                {
                    "type": "formatted-num",
                    "targets": [2, 3],
                },
                
                { "orderable": false, "targets": 4 }
            ]            
        });        
    });
</script>