<?php
if ($modosithato) {
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <?php echo $this->formRow($form->get('id')); ?>

    <div class="form-group">
        <?php echo $this->formRow($form->get('auto')); ?>
        <span class="help-block" id="help_<?php echo $form->get('auto')->getAttribute('id') ?>"></span>
    </div>

    <div class="form-group">
        <?php echo $this->formRow($form->get('tipus')); ?>
        <span class="help-block" id="help_<?php echo $form->get('tipus')->getAttribute('id') ?>"></span>
    </div>

    <?php
    if ($form->get('tipus')->getValue() == \Application\Entity\Autokoltseg::UZEMANYAG_TIPUS) :
        $koltsegnevHide = 'hide';
    endif;
    ?>

    <div class="form-group <?php echo $koltsegnevHide ?>" id="koltsegnev_holder">
        <?php echo $this->formRow($form->get('koltsegnev')); ?>
        <span class="help-block" id="help_<?php echo $form->get('koltsegnev')->getAttribute('id') ?>"></span>
    </div>

    <div class="form-group">
        <?php echo $this->formRow($form->get('osszeg')); ?>
        <span class="help-block" id="help_<?php echo $form->get('osszeg')->getAttribute('id') ?>"></span>
    </div>

    <div class="form-group">
        <?php echo $this->formRow($form->get('datum')); ?>
        <span class="help-block" id="help_<?php echo $form->get('datum')->getAttribute('id') ?>"></span>
    </div>

    <?php echo $this->form()->closeTag($form); ?>

    <script>
        $(document).ready(function() {
            $("#tipus").change(function() {
                if($("#koltsegnev_holder").hasClass('hide')) {
                    $("#koltsegnev_holder").removeClass('hide');
                    $("#koltsegnev").val('');
                } else {
                    $("#koltsegnev_holder").addClass('hide');
                    $("#koltsegnev").val('<?php echo \Application\Entity\Autokoltseg::UZEMANYAG_STRING ?>');
                }
            });
        });
    </script>
    <?php
} else {
    ?>
    <div class="error-text"><?php echo $this->translate('Ezt az költséget már nem módosíthatod!'); ?></div>
    <?php
}
?>    