<h2><?php echo $this->translate('Autók') ?></h2>
<hr />
<div class="hide" id="modal_title_new"><?php echo $this->translate('Új autó bevezetése'); ?></div>
<div class="hide" id="torol_confirm_text"><?php echo $this->translate('Biztosan törlöd az autót?'); ?></div>
<div class="hide" id="modal_title_edit"><?php echo $this->translate('Autó adatainak módosítása'); ?></div>
<div class="hide" id="modal_getformurl"><?php echo $this->url('kocsi', array('action' => 'getform')) ?></div>
<div class="hide" id="modal_saveformurl"><?php echo $this->url('kocsi', array('action' => 'saveform')) ?></div>
<div class="hide" id="delete_url"><?php echo $this->url('kocsi', array('action' => 'delete')) ?></div>
<div class="hide" id="ajax_error_message"><?php echo $this->translate('Hiba! A műveletet nem sikerült végrehajtani!'); ?></div>
<div class="hide" id="saveFormCallbackFuncName">saveAutoCallback</div>

<input type="hidden" id="isAllowedEdit" value="<?php echo ($this->isAllowed('auto', 'modosit') ? 1 : 0); ?>" />
<input type="hidden" id="isAllowedDelete" value="<?php echo ($this->isAllowed('auto', 'torol') ? 1 : 0); ?>" />
       
<?php $dataTableId = 'autok_table' ?>

<?php
if ($this->isAllowed('auto', 'letrehoz')) :
    ?>

    <a href="javascript:void(0)" class="create_edit" id="object_0">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Új autó felvétele'); ?>
    </a>
    <br /><br />
    <?php
endif;
?>

<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered myDataTable" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Rendszám'); ?></th>
            <th><?php echo $this->translate('Műveletek'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($autok)) :
            foreach ($autok as $auto) {
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($auto->getRendszam()) ?></td>
                    <td>
                        <?php
                        if ($this->isAllowed('auto', 'modosit')) :
                            ?>
                            <a href="javascript:void(0)" class="create_edit" id="object_<?php echo $auto->getId() ?>" title="<?php echo $this->translate('Módosítás'); ?>">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <?php
                        endif;

                        if ($this->isAllowed('auto', 'torol')) :
                            ?>
                            <a href="javascript:void(0)" class="torol" id="object_torol_<?php echo $auto->getId() ?>" title="<?php echo $this->translate('Törlés'); ?>">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                            <?php
                        endif;
                        ?>
                    </td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
</table>

<?php echo $this->partial('/application/partial_modal.phtml'); ?>

<script>
    $(document).ready(function() {
        $("#<?php echo $dataTableId ?>").dataTable({
            language: {
                url: '/js/DataTables-1.10.2/localization/Hungarian.json'
            },
            "columnDefs": [                
                { "orderable": false, "targets": 1 }
            ]            
        });        
    });
</script>