<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('osszeg')); ?>
    <span class="help-block" id="help_<?php echo $form->get('osszeg')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('datum')); ?>
    <span class="help-block" id="help_<?php echo $form->get('datum')->getAttribute('id') ?>"></span>
</div>

<?php echo $this->form()->closeTag($form); ?>
