<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('cegname')); ?>
    <span class="help-block" id="help_<?php echo $form->get('cegname')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('szerzodesdatum')); ?>
    <span class="help-block" id="help_<?php echo $form->get('szerzodesdatum')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('idotartam')); ?>
    <span class="help-block" id="help_<?php echo $form->get('idotartam')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formCheckbox($form->get('automatikushosszabbitas')) ?>
    <label for="automatikushosszabbitas"><?php echo $form->get('automatikushosszabbitas')->getLabel() ?></label>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('fizetesihatarido')); ?>
    <span class="help-block" id="help_<?php echo $form->get('fizetesihatarido')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formCheckbox($form->get('szazalekmunkas')) ?>
    <label for="szazalekmunkas"><?php echo $form->get('szazalekmunkas')->getLabel() ?></label>
</div>

<?php echo $this->form()->closeTag($form); ?>

    <script>
        $(document).ready(function() {
            if ($("#id").val() == '') {
                $("#szazalekmunkas").prop('checked', true);
            }
        });
    </script>

