<h2><?php echo $this->translate('Szerződések') ?></h2>
<hr />
<div class="hide" id="modal_title_new"><?php echo $this->translate('Új szerződés bevezetése'); ?></div>
<div class="hide" id="torol_confirm_text"><?php echo $this->translate('Biztosan törlöd a szerződést?'); ?></div>
<div class="hide" id="modal_title_edit"><?php echo $this->translate('Cég adatainak módosítása'); ?></div>
<div class="hide" id="modal_getformurl"><?php echo $this->url('ceg', array('action' => 'getform')) ?></div>
<div class="hide" id="modal_saveformurl"><?php echo $this->url('ceg', array('action' => 'saveform')) ?></div>
<div class="hide" id="delete_url"><?php echo $this->url('ceg', array('action' => 'delete')) ?></div>
<div class="hide" id="ajax_error_message"><?php echo $this->translate('Hiba! A műveletet nem sikerült végrehajtani!'); ?></div>
<div class="hide" id="saveFormCallbackFuncName">saveCegCallback</div>

<input type="hidden" id="isAllowedEdit" value="<?php echo ($this->isAllowed('ceg', 'modosit') ? 1 : 0); ?>" />
<input type="hidden" id="isAllowedDelete" value="<?php echo ($this->isAllowed('ceg', 'torol') ? 1 : 0); ?>" />
       
<?php $dataTableId = 'cegek_table' ?>

<?php
if ($this->isAllowed('ceg', 'letrehoz')) :
    ?>

    <a href="javascript:void(0)" class="create_edit" id="object_0">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Új szerződés bevezetése'); ?>
    </a>
    <br /><br />
    <?php
endif;
?>

<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered myDataTable" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Cég neve'); ?></th>
            <th><?php echo $this->translate('Ekezet nelkuli nev'); ?></th>
            <th><?php echo $this->translate('Szerződés <br>dátuma'); ?></th>
            <th><?php echo $this->translate('Szerződés <br>időtartama'); ?></th>
            <th><?php echo $this->translate('Automatikus <br>hosszabítás'); ?></th>
            <th><?php echo $this->translate('Fizetési <br>határidő'); ?></th>
            <th><?php echo $this->translate('Műveletek'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($cegek)) :
            foreach ($cegek as $ceg) {
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($ceg->getCegname()) ?></td>
                    <td><?php echo $this->accent_trimmer($this->escapeHtml($ceg->getCegname())) ?></td>
                    <td><?php echo $ceg->getSzerzodesdatum()->format('Y-m-d') ?></td>
                    <td><?php echo $this->escapeHtml($ceg->getIdotartam()) .  ' ' . $this->translate('hónap') ?></td>
                    <td><?php echo $ceg->getAutomatikusHosszabbitas() ? $this->translate('Igen') : $this->translate('Nem') ?></td>
                    <td>
                        <?php 
                        switch ($ceg->getFizetesihatarido()) {
                            case -1: echo $this->translate('Minden hónap végén');
                                break;
                            case 0: echo $this->translate('Azonnal');
                                break;
                            default:
                                echo $this->escapeHtml($ceg->getFizetesihatarido()) .  ' ' . $this->translate('nap');
                        }
                        ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url('ceg', array('action' => 'view', 'id' => $ceg->getId())) ?>" title="<?php echo $this->translate('Részletek'); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <?php
                        if ($this->isAllowed('ceg', 'modosit')) :
                            ?>
                            <a href="javascript:void(0)" class="create_edit" id="object_<?php echo $ceg->getId() ?>" title="<?php echo $this->translate('Módosítás'); ?>">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <?php
                        endif;

                        if ($this->isAllowed('ceg', 'torol')) :
                            ?>
                            <a href="javascript:void(0)" class="torol" id="object_torol_<?php echo $ceg->getId() ?>" title="<?php echo $this->translate('Törlés'); ?>">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                            <?php
                        endif;
                        ?>
                    </td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
</table>

<?php echo $this->partial('/application/partial_modal.phtml'); ?>

<script>
    $(document).ready(function() {
        $("#<?php echo $dataTableId ?>").dataTable({
            language: {
                url: '/js/DataTables-1.10.2/localization/Hungarian.json'
            },
            "columnDefs": [
                {
                    "targets": [ 1 ],
                    "visible": false,
                },
                
                { "orderable": false, "targets": 6 }
            ]            
        });        
    });
</script>