<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('username')); ?>
    <span class="help-block" id="help_<?php echo $form->get('username')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
    <span class="help-block" id="help_<?php echo $form->get('password')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('roles')); ?>
    <span class="help-block" id="help_<?php echo $form->get('roles')->getAttribute('id') ?>"></span>
</div>

<?php echo $this->form()->closeTag($form); ?>
