<h2><?php echo $this->translate('Felhasználók') ?></h2>
<hr />
<div class="hide" id="modal_title_new"><?php echo $this->translate('Új felhasználó bevezetése'); ?></div>
<div class="hide" id="torol_confirm_text"><?php echo $this->translate('Biztosan törlöd a felhasználót?'); ?></div>
<div class="hide" id="modal_title_edit"><?php echo $this->translate('Felhasználó adatainak módosítása'); ?></div>
<div class="hide" id="modal_getformurl"><?php echo $this->url('zfcuser-getform', array('action' => 'getform')) ?></div>
<div class="hide" id="modal_saveformurl"><?php echo $this->url('zfcuser-saveform', array('action' => 'saveform')) ?></div>
<div class="hide" id="delete_url"><?php echo $this->url('zfcuser-delete', array('action' => 'delete')) ?></div>
<div class="hide" id="ajax_error_message"><?php echo $this->translate('Hiba! A műveletet nem sikerült végrehajtani!'); ?></div>
<div class="hide" id="saveFormCallbackFuncName">saveUserCallback</div>

<input type="hidden" id="isAllowedEdit" value="<?php echo ($this->isAllowed('user', 'modosit') ? 1 : 0); ?>" />
<input type="hidden" id="isAllowedDelete" value="<?php echo ($this->isAllowed('user', 'torol') ? 1 : 0); ?>" />

<?php $dataTableId = 'felhasznalok_table' ?>

<?php
if ($this->isAllowed('user', 'letrehoz')) :
    ?>
    <a href="javascript:void(0)" class="create_edit" id="object_0">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Új felhasználó felvétele'); ?>
    </a>
    <br /><br />
    <?php
endif;
?>
<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered myDataTable" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Felhasználónév'); ?></th>
            <th><?php echo $this->translate('Jogosultság'); ?></th>
            <th><?php echo $this->translate('Műveletek'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($users)) :
            foreach ($users as $user) {
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($user->getUsername()) ?></td>
                    <td><?php echo $user->getRolesString() ?></td>
                    <td>
                        <?php
                        if ($this->isAllowed('user', 'modosit')) :
                            ?>
                            <a href="javascript:void(0)" class="create_edit" id="object_<?php echo $user->getId() ?>" title="<?php echo $this->translate('Módosítás'); ?>">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <?php
                        endif;

                        if ($this->isAllowed('user', 'torol') && $user->getId() != $loginId) :
                            ?>
                            <a href="javascript:void(0)" class="torol" id="object_torol_<?php echo $user->getId() ?>" title="<?php echo $this->translate('Törlés'); ?>">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                            <?php
                        endif;
                        ?>
                    </td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
</table>

<?php echo $this->partial('/application/partial_modal.phtml'); ?>

<script>
    $(document).ready(function() {
        $("#<?php echo $dataTableId ?>").dataTable({
            language: {
                url: '/js/DataTables-1.10.2/localization/Hungarian.json'
            },
            "columnDefs": [                
                { "orderable": false, "targets": 2 }
            ]            
        });        
    });
</script>