<?php $dataTableId = 'lezart_tartozasok_table' ?>
<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Tartozás neve'); ?></th>
            <th><?php echo $this->translate('Ekezet nelkuli nev'); ?></th>
            <th><?php echo $this->translate('Összeg'); ?></th>
            <th><?php echo $this->translate('Összeg szam'); ?></th>
            <th><?php echo $this->translate('Dátum'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $osszHo = 0;
        if (count($lezart_tartozasok)) :
            foreach ($lezart_tartozasok as $tartozas) {
                $osszHo += $tartozas->getOsszeg();
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($tartozas->getTartozasnev()) ?></td>
                    <td><?php echo $this->accent_trimmer($this->escapeHtml($tartozas->getTartozasnev())) ?></td>
                    <td><?php echo $this->escapeHtml($tartozas->getOsszeg()) ?> RON</td>
                    <td><?php echo $this->escapeHtml($tartozas->getOsszeg()) ?></td>
                    <td><?php echo $tartozas->getDatum()->format('Y-m-d'); ?></td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
    <tfoot>
        <tr>
            <th colspan="5"><?php echo $this->translate('Összeg:') . ' <span id="vegosszeg_lezart">' . number_format($osszHo, 2) . '</span> RON'; ?></td>
        </tr>
    </tfoot>
</table>

<script>
    $(document).ready(function() {
        $("#<?php echo $dataTableId ?>").dataTable({
            "order": [[ 4, "asc" ]],
            drawCallback: function () {
                  var api = this.api();
                  var sum;
                  if(api.column(3, {filter:'applied'}).data().length)
                      sum = api.column(3, {filter:'applied'}).data().sum();
                  else
                      sum = 0;
                    $("#vegosszeg_lezart").html(sum);
                },     
            language: {
                url: '/js/DataTables-1.10.2/localization/Hungarian.json'
            },
            "columnDefs": [
                {
                    "targets": [ 1, 3 ],
                    "visible": false,
                },
                
                {
                    "type": "formatted-num",
                    "targets": [2],
                },
            ]            
        });
    });
</script>