<h2><?php echo $this->translate('Alkalmazottak') ?></h2>
<hr />
<div class="hide" id="modal_title_new"><?php echo $this->translate('Új munkás bevezetése'); ?></div>
<div class="hide" id="torol_confirm_text"><?php echo $this->translate('Biztosan törlöd a munkást?'); ?></div>
<div class="hide" id="modal_title_edit"><?php echo $this->translate('Munkás adatainak módosítása'); ?></div>
<div class="hide" id="modal_getformurl"><?php echo $this->url('munkas', array('action' => 'getform')) ?></div>
<div class="hide" id="modal_saveformurl"><?php echo $this->url('munkas', array('action' => 'saveform')) ?></div>
<div class="hide" id="delete_url"><?php echo $this->url('munkas', array('action' => 'delete')) ?></div>
<div class="hide" id="ajax_error_message"><?php echo $this->translate('Hiba! A műveletet nem sikerült végrehajtani!'); ?></div>
<div class="hide" id="saveFormCallbackFuncName">saveMunkasCallback</div>

<div class="hide" id="today"><?php $now = new \DateTime(); echo $now->format('Y-m-d'); ?></div>

<input type="hidden" id="isAllowedEdit" value="<?php echo ($this->isAllowed('munkas', 'modosit') ? 1 : 0); ?>" />
<input type="hidden" id="isAllowedDelete" value="<?php echo ($this->isAllowed('munkas', 'torol') ? 1 : 0); ?>" />
       
<?php $dataTableId = 'munkasok_table' ?>

<?php
if ($this->isAllowed('munkas', 'letrehoz')) :
    ?>

    <a href="javascript:void(0)" class="create_edit" id="object_0">
        <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Új munkás felvétele'); ?>
    </a>
    <br /><br />
    <?php
endif;
?>

<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered myDataTable" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Név'); ?></th>
            <th><?php echo $this->translate('Ekezet nelkuli nev'); ?></th>
            <th><?php echo $this->translate('Típus'); ?></th>
            <th><?php echo $this->translate('Hely'); ?></th>
            <th><?php echo $this->translate('Ekezet nelkuli hely'); ?></th>
            <th><?php echo $this->translate('Alk. dátuma'); ?></th>
            <th><?php echo $this->translate('Szülinap'); ?></th>
            <th><?php echo $this->translate('Havi fix fizetés'); ?></th>
            <th><?php echo $this->translate('Műveletek'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($munkasok)) :
            foreach ($munkasok as $munkas) {
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($munkas->getName()) ?></td>
                    <td><?php echo $this->accent_trimmer($this->escapeHtml($munkas->getName())) ?></td>
                    <td><?php echo $this->escapeHtml($munkas->getMunkastipus()->getTipusnev()) ?></td>
                    <td><?php echo $this->escapeHtml($munkas->getHelyString()) ?></td>
                    <td><?php echo $this->accent_trimmer($this->escapeHtml($munkas->getHelyString())) ?></td>
                    <td><?php echo $munkas->getHireDate()->format('Y-m-d') ?></td>
                    <td><?php echo $munkas->getBirthdate() ? $munkas->getBirthdate()->format('Y-m-d') : '' ?></td>
                    <td>
                        <?php echo $fixFizetesekArray[$munkas->getId()]; ?> RON
                    </td>
                    <td>
                        <a href="<?php echo $this->url('munkas', array('action' => 'egyenleg', 'id' => $munkas->getId())) ?>" title="<?php echo $this->translate('Egyenleg'); ?>">
                            <span class="glyphicon glyphicon-usd"></span>
                        </a>
                        
                        <?php
                        if ($this->isAllowed('munkas', 'modosit')) :
                            ?>
                            <a href="javascript:void(0)" class="create_edit" id="object_<?php echo $munkas->getId() ?>" title="<?php echo $this->translate('Módosítás'); ?>">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <?php
                        endif;

                        if ($this->isAllowed('munkas', 'torol')) :
                            ?>
                            <a href="javascript:void(0)" class="torol" id="object_torol_<?php echo $munkas->getId() ?>" title="<?php echo $this->translate('Törlés'); ?>">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                            <?php
                        endif;
                        ?>
                    </td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
</table>

<?php echo $this->partial('/application/partial_modal.phtml'); ?>

<script>
    $(document).ready(function() {
        $("#<?php echo $dataTableId ?>").dataTable({
            language: {
                url: '/js/DataTables-1.10.2/localization/Hungarian.json'
            },
            "columnDefs": [
                {
                    "targets": [ 1, 4 ],
                    "visible": false,
                },
                
                { "orderable": false, "targets": 8 }
            ]            
        });        
    });
</script>