<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formRow($form->get('id')); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('nev')); ?>
    <span class="help-block" id="help_<?php echo $form->get('nev')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('mennyiseg')); ?>
    <span class="help-block" id="help_<?php echo $form->get('mennyiseg')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('tejmennyiseg')); ?>
    <span class="help-block" id="help_<?php echo $form->get('tejmennyiseg')->getAttribute('id') ?>"></span>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('ar')); ?>
    <span class="help-block" id="help_<?php echo $form->get('ar')->getAttribute('id') ?>"></span>
</div>

<?php echo $this->form()->closeTag($form); ?>