<h2><?php echo $this->translate('Kávéfajták') ?></h2>
<hr />
<div class="hide" id="modal_title_new"><?php echo $this->translate('Új kávéfajta bevezetése'); ?></div>
<div class="hide" id="torol_confirm_text"><?php echo $this->translate('Biztosan törlöd a kávéfajtaet?'); ?></div>
<div class="hide" id="modal_title_edit"><?php echo $this->translate('Kávéfajta adatainak módosítása'); ?></div>
<div class="hide" id="modal_getformurl"><?php echo $this->url('kavefajta', array('action' => 'getform')) ?></div>
<div class="hide" id="modal_saveformurl"><?php echo $this->url('kavefajta', array('action' => 'saveform')) ?></div>
<div class="hide" id="delete_url"><?php echo $this->url('kavefajta', array('action' => 'delete')) ?></div>
<div class="hide" id="ajax_error_message"><?php echo $this->translate('Hiba! A műveletet nem sikerült végrehajtani!'); ?></div>
<div class="hide" id="saveFormCallbackFuncName">saveKavefajtaCallback</div>
       
<?php $dataTableId = 'kavefajtak_table' ?>

<a href="javascript:void(0)" class="create_edit" id="object_0">
	<span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Új kávéfajta bevitele'); ?>
</a>
<br /><br />

<table id="<?php echo $dataTableId ?>" class="table table-striped table-bordered" width="100%">
    <thead>
        <tr>
            <th><?php echo $this->translate('Kávéfajta neve'); ?></th>
			<th><?php echo $this->translate('Kávémennyiség (gram)'); ?></th>
			<th><?php echo $this->translate('Tejmennyiség (ml)'); ?></th>
			<th><?php echo $this->translate('Eladási ár'); ?></th>
            <th><?php echo $this->translate('Műveletek'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($kavefajtak)) :
            foreach ($kavefajtak as $kavefajta) {
                ?>
                <tr>
                    <td><?php echo $this->escapeHtml($kavefajta->getNev()) ?></td>
					<td><?php echo $this->escapeHtml($kavefajta->getMennyiseg()) ?></td>
					<td><?php echo $this->escapeHtml($kavefajta->getTejmennyiseg()) ?></td>
					<td><?php echo $this->escapeHtml($kavefajta->getAr()) ?></td>
                    <td>
						<a href="javascript:void(0)" class="create_edit" id="object_<?php echo $kavefajta->getId() ?>" title="<?php echo $this->translate('Módosítás'); ?>">
							<span class="glyphicon glyphicon-pencil"></span>
						</a>

						<a href="javascript:void(0)" class="torol_kavefajta" id="object_torol_<?php echo $kavefajta->getId() ?>" title="<?php echo $this->translate('Törlés'); ?>">
							<span class="glyphicon glyphicon-remove"></span>
						</a>
                    </td>
                </tr>
                <?php
            }
        endif;
        ?>        
    </tbody>
</table>

<?php echo $this->partial('/application/partial_modal.phtml'); ?>

<script>
$(document).ready(function() {	
    $("body").on('click', '.torol_kavefajta', function() {
        var $row = $(this).parents('tr');
        if (confirm($("#torol_confirm_text").text())) {
            var id = $(this).attr('id').replace('object_torol_', '');
            var url = $("#delete_url").html();
            $.post(url, {'id' : id}, function(resp) {
                if (resp == 'success') {
                    $row.remove();
                    $.sticky($("#modal_success").html(), {classList: 'success', autoclose: 4000,  position: 'top-right'});
                } else if(resp == 'nodelete') {
                    $("#globalModal .modal-body").html($("#modal_nodelete").html());
                    $("button.btn-primary").hide();
                    $("#globalModal").modal();         
                } else {
                    $.sticky($("#ajax_error_message").html(), {classList: 'error', autoclose: 4000,  position: 'top-right'});
                }
            });
        }
    });
});
</script>