<?php
if ($modosithato) {
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <?php echo $this->formRow($form->get('munkas_id')); ?>
    <?php echo $this->formRow($form->get('id')); ?>

    <div class="form-group">
        <?php echo $this->formRow($form->get('tartozasnev')); ?>
        <span class="help-block" id="help_<?php echo $form->get('tartozasnev')->getAttribute('id') ?>"></span>
    </div>

    <div class="form-group">
        <?php echo $this->formRow($form->get('osszeg')); ?>
        <span class="help-block" id="help_<?php echo $form->get('osszeg')->getAttribute('id') ?>"></span>
    </div>

    <div class="form-group">
        <?php echo $this->formRow($form->get('datum')); ?>
        <span class="help-block" id="help_<?php echo $form->get('datum')->getAttribute('id') ?>"></span>
    </div>

    <?php echo $this->form()->closeTag($form); ?>
    <?php
} else {
    ?>
    <div class="error-text"><?php echo $this->translate('Ezt az költséget már nem módosíthatod!'); ?></div>
    <?php
}
?>